name: UnityBuild

on: [pull_request]

jobs:
  editorTestJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2019.3.7f1]

    steps:
    - uses: actions/checkout@master
    - name: create License
      run: openssl aes-256-cbc -d -in Unity_v2019.x.ulf-cipher -k ${CYPHER_KEY} -md md5 >> ./License.ulf
      env:
          CYPHER_KEY: ${{ secrets.CYPHER_KEY }}
    - name: load License
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile ./License.ulf || exit 0
    - name: ls
      run: |
          CURRENT_DIR=`pwd`
          echo ${CURRENT_DIR}
    - name: test-editmode
      run: |
          /opt/Unity/Editor/Unity -quit -batchmode -nographics -projectPath . -runEditorTests -testPlatform editmode || exit 0
    - name: result
      run: |
          ls -la
    - uses: actions/upload-artifact@master
      with:
        name: Build
        path: test-results
        
