name: UnityBuild

on: [pull_request]

jobs:
  EditorTest:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2019.3.7f1]

    steps:
    - uses: actions/checkout@master
    - name: create License
      run: openssl aes-256-cbc -d -in Unity_v2019.x.ulf-cipher -k ${CYPHER_KEY} -md md5 >> ./License.ulf
      env:
          CYPHER_KEY: ${{ secrets.CYPHER_KEY }}
    - name: load License
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile ./License.ulf || exit 0
    - name: ls
      run: |
          ls -la
    - name: test-editmode
      run: |
          /opt/Unity/Editor/Unity -batchmode -nographics -projectPath . -logFile ./_Build/build.log \
          -testPlatform editmode -runEditorTests  \
          -editorTestsResultFile ./_Build/test-results.xml || exit 0
    - name: ls
      run: |
          ls -la
          ls -la _Build
    - uses: actions/upload-artifact@master
      with:
        name: EditorModeResult_${{ matrix.unity-tag }}
        path: ./_Build
        
  PlayTest:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2019.3.7f1, 2019.3.7f1-linux-il2cpp, 2019.3.7f1-android, 2019.3.7f1-ios, 2019.3.7f1-webgl, 2019.3.7f1-windows, 2019.3.7f1-mac]

    steps:
    - uses: actions/checkout@master
    - name: chrome
      run: |
          apk add -U unzip && rm -rf /var/cache/apk/*
          wget https://download-chromium.appspot.com/dl/Linux_ChromiumOS_Full?type=snapshots
          unzip chrome-linux.zip
          cd chrome-linux
          sudo cp ./chrome_sandbox /usr/local/sbin/chrome-devel-sandbox
          sudo chown root:root /usr/local/sbin/chrome-devel-sandbox
          sudo chmod 4755 /usr/local/sbin/chrome-devel-sandbox
          cd ..
    - name: create License
      run: openssl aes-256-cbc -d -in Unity_v2019.x.ulf-cipher -k ${CYPHER_KEY} -md md5 >> ./License.ulf
      env:
          CYPHER_KEY: ${{ secrets.CYPHER_KEY }}
    - name: load License
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile ./License.ulf || exit 0
    - name: ls
      run: |
          ls -la
    - name: test-playmode
      run: |
          /opt/Unity/Editor/Unity -batchmode -nographics -projectPath . -logFile ./_Build/build.log \
          -runTests -testPlatform StandaloneLinux64 \
          -testResults ./_Build/test-results.xml || exit 0
    - name: cat log
      run: |
          cat ./_Build/build.log
    - name: ls
      run: |
          ls -la
          ls -la _Build
    - uses: actions/upload-artifact@master
      with:
        name: PlayModeResult_${{ matrix.unity-tag }}
        path: ./_Build    
